### ISSUE TITLE
homebrew: Invalid formula: formulae require at least a URL

### ISSUE THREAD

**Issue by gisle** [humio/cli#101]
I tried to follow the instructions on how to install humioctl using homebrew on a M1 Mac but I failures from the first step.

```
$ brew tap humio/humio
==> Tapping humio/humio
Cloning into '/opt/homebrew/Library/Taps/humio/homebrew-humio'...
remote: Enumerating objects: 155, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 155 (delta 13), reused 3 (delta 0), pack-reused 95
Receiving objects: 100% (155/155), 22.87 KiB | 1.63 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/humio/homebrew-humio/Formula/humioctl.rb
formulae require at least a URL
Error: Cannot tap humio/humio: invalid syntax in tap!

$ brew --version
Homebrew 3.3.14
Homebrew/homebrew-core (git revision 3398a5ff801; last commit 2022-02-12)
Homebrew/homebrew-cask (git revision a4bce851fd; last commit 2022-02-12)
```

**Comment by SaaldjorMike** [comment]
Could you perhaps share a few details about the system you are trying to install this on? The formula is here: https://github.com/humio/homebrew-humio/blob/master/Formula/humioctl.rb

Are you perhaps using an M1-based MacBook? If so, then that error sounds like something I'd expect given that the formula currently doesn't include support for those CPU's. In order to make that work we likely need to make adjustments to https://github.com/humio/cli/blob/master/.goreleaser.yaml#L3-L11 to include support for Arm-based CPU's. In the mean time you can install it using `go install ...` as shown here: https://github.com/humio/cli/blob/master/README.md?plain=1#L37
